// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ModelformUni: typeof import('./../components/Modelform/Uni.vue')['default']
    ModelformUniMiniButton: typeof import('./../components/Modelform/UniMiniButton.vue')['default']
    ModelformUniTableField: typeof import('./../components/Modelform/UniTableField.vue')['default']
    ModelformUniWidget: typeof import('./../components/Modelform/UniWidget.vue')['default']
    PageLayout: typeof import('./../components/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WxAvatar: typeof import('./../components/wx-avatar.vue')['default']
    XButton: typeof import('./../components/x-button.vue')['default']
  }
}
